version: "2"
services:
  application:
    image: busybox
    volumes:
      - ./app/static:/home/node/app/static

  appa:
    build:
      context: .
    volumes_from: 
      - application
    depends_on:
      - application
    expose:
      - 3001
    networks:
      backend:
    environment:
      - ANOTHER_SERVER_HOST=appb
      - ANOTHER_SERVER_PORT=3002
      - PORT=3001
      - SERVER_NAME=appa

  appb:
    build:
      context: .
    volumes_from: 
      - application
    depends_on:
      - application
    expose:
      - 3002
    networks:
      backend:
    environment:
      - ANOTHER_SERVER_HOST=appa
      - ANOTHER_SERVER_PORT=3001
      - PORT=3002
      - SERVER_NAME=appb

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    depends_on:
      - appa
      - appb
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./nginxcache:/var/cache/nginx
    networks:
      backend:
      frontend:

networks:
  backend:
    internal: true
  frontend: