apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nick-ingress
  namespace: nick-space
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: koa-a-com-tls
      hosts:
        - koa-a.com
  rules:
    - host: koa-a.com
      http:
        paths:
        - backend:
            serviceName: nick-service-a
            servicePort: 3001
    - host: koa-b.com
      http:
        paths:
        - backend:
            serviceName: nick-service-b
            servicePort: 3002
    
    # - http:
    #   paths:
    #   - path: /testa
    #     backend:
    #       serviceName: nick-service-a
    #       servicePort: 3001
    #   - path: /testb
    #     backend:
    #       serviceName: nick-service-b
    #       servicePort: 3002